# src/Ens/JobeetBundle/Resources/config/routing.yml

login:
    pattern: /login
    defaults: { _controller: EnsJobeetBundle:Default:login }

login_check:
    pattern: /login_check

logout:
    pattern: /logout

EnsJobeetBundle_category:
    pattern: /category/{slug}/{page}
    defaults: { _controller: EnsJobeetBundle:Category:show, page: 1 }

EnsJobeetBundle_job:
    resource: "@EnsJobeetBundle/Resources/config/routing/job.yml"
    prefix: /job

EnsJobeetBundle_homepage:
    pattern: /
    defaults: { _controller: EnsJobeetBundle:Job:index }